services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mentis
      POSTGRES_USER: mentis
      POSTGRES_PASSWORD: mentis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mentis"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:v1.7.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  mentis:
    build: .
    depends_on:
      - postgres
      - qdrant
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://mentis:mentis@postgres:5432/mentis?sslmode=disable
      QDRANT_URL: http://qdrant:6333
      QDRANT_COLLECTION: mentis
      SERVER_PORT: 8080
      LOG_LEVEL: info
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data: